version: '3'

services:

  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    restart: always
    build:
      context: ./docker/php
      args:
        UID: $UID
        GUID: $GUID
    volumes:
      - ./:/app

  mysql:
    restart: always
    build:
      context: ./docker/mysql
      args:
        UID: $UID
        GUID: $GUID
    environment:
      TZ: $MYSQL_TZ
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/backup/:/backup
    ports:
      - $MYSQL_PORT:3307

  phpmyadmin:
    restart: always
    image: phpmyadmin:5
    ports:
      - $PMA_PORT:80
    environment:
      PMA_HOST: mysql
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - mysql

volumes:
  mysql-data:
